
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.StringTokenizer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author E-Therng
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        Extras.setEnabled(false);
        Extras.setVisible(false);
        try{
            String game = "";
            FileReader fr = new FileReader("Extra.txt");
                BufferedReader br = new BufferedReader(fr);
                String r ="";
                
                while((r=br.readLine())!=null)
                {
                    StringTokenizer tk = new StringTokenizer(r,"|");
                    game = r;
                }
                br.close();
                System.out.println(game);
                if(game.equals("1"))
                {
                    Extras.setEnabled(true);
                    Extras.setVisible(true);
                }
        }
        catch(Exception e)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GoToHow = new javax.swing.JButton();
        Resume = new javax.swing.JButton();
        GoToCredits = new javax.swing.JButton();
        GoToStart1 = new javax.swing.JButton();
        Extras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("SEVEN DAYS");

        GoToHow.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        GoToHow.setText("How To Play");
        GoToHow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToHowActionPerformed(evt);
            }
        });

        Resume.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Resume.setText("Resume Game");
        Resume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResumeActionPerformed(evt);
            }
        });

        GoToCredits.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        GoToCredits.setText("Credits");
        GoToCredits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToCreditsActionPerformed(evt);
            }
        });

        GoToStart1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        GoToStart1.setText("New Game");
        GoToStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoToStart1ActionPerformed(evt);
            }
        });

        Extras.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Extras.setText("Extras");
        Extras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoToHow, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resume, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoToCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoToStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Extras, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GoToHow, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoToStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Resume, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GoToCredits, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Extras, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoToHowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToHowActionPerformed
        setContentPane(new HowToPlay());
        pack();
    }//GEN-LAST:event_GoToHowActionPerformed

    private void ResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResumeActionPerformed
        String day = "";
        try{
            FileReader fr = new FileReader("Day.txt");
                BufferedReader br = new BufferedReader(fr);
                String r ="";
                
                while((r=br.readLine())!=null)
                {
                    StringTokenizer tk = new StringTokenizer(r,"|");
                    day = r;
                }
                br.close();
        }
        catch(Exception e)
        {
            
        }
        if(day.equals("0") || day.equals("2.1") || day.equals("Hunger") || day.equals("Thirst") || day.equals("3 outside") || day.equals("3 survivor")
                || day.equals("3 survivor befriend") || day.equals("3 supermarket") || day.equals("3 supermarket kill alien") || day.equals("3 supermarket steal")
                || day.equals("6 shoot") || day.equals("7 outside") || day.equals("7 survivor") || day.equals("7 survivor befriend") || day.equals("7 supermarket")
                || day.equals("7 supermarket kill alien") || day.equals("7 supermarket steal"))
        {
            TextScreen f1 = new TextScreen();

        f1.setVisible(true);
        this.setVisible(false);
        }
        if(day.equals("1") || day.equals("2") || day.equals("3") || day.equals("3 return home") || day.equals("4") || day.equals("5") || day.equals("5 meds")
                || day.equals("5 no meds") || day.equals("6 sleep")||day.equals("6 sleep") || day.equals("6 no sleep") || day.equals("6 no shoot") || day.equals("7"))
        {
            Bunker f1 = new Bunker();

        f1.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_ResumeActionPerformed

    private void GoToCreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToCreditsActionPerformed
        setContentPane(new Credits());
        pack();
    }//GEN-LAST:event_GoToCreditsActionPerformed

    private void GoToStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoToStart1ActionPerformed
        try{
            FileWriter Day = new FileWriter("Day.txt");
                    PrintWriter BookWriter = new PrintWriter(Day);
                    
                    BookWriter.println("0") ;
                    BookWriter.close();
                    
        }
        catch(Exception e)
          {
              
          }
                    
        TextScreen f1 = new TextScreen();

        f1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GoToStart1ActionPerformed

    private void ExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtrasActionPerformed
        setContentPane(new ExtraContent());
        pack();
    }//GEN-LAST:event_ExtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Extras;
    private javax.swing.JButton GoToCredits;
    private javax.swing.JButton GoToHow;
    private javax.swing.JButton GoToStart1;
    private javax.swing.JButton Resume;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
